import {readFile, writeFile, mkdir, access} from 'node:fs/promises'
import {dirname, resolve} from 'node:path'
import {fileURLToPath} from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const exists = async path => access(path).then(() => true, () => false)
const args = process.argv.slice(2).filter(arg => arg !== '--check')
const sourcePath = resolve(args[0] ?? (await exists(resolve(root, 'review-dark-mode.user.js'))
    ? resolve(root, 'review-dark-mode.user.js')
    : resolve(root, 'src/scripts/review-dark-mode.user.js')))
const outputPath = resolve(args[1] ?? (sourcePath.endsWith('/src/scripts/review-dark-mode.user.js')
    ? resolve(root, 'src/styles/wanikani-dark-mode.user.css')
    : resolve(root, 'wanikani-dark-mode.user.css')))
const source = await readFile(sourcePath, 'utf8')
const metadata = key => {
    const value = source.match(new RegExp(`^// @${key}\\s+(.+)$`, 'm'))?.[1]
    if (!value) throw new Error(`Missing userscript metadata: ${key}`)
    return value
}
const template = source.match(/style\.textContent = `([\s\S]*?)`/)
if (!template) throw new Error('Could not find the shared CSS template')
// Fail if the template gains JS escapes or interpolation this converter cannot handle.
if (template[1].includes('\\')) throw new Error('CSS template now contains escapes; update the converter')

// :root replaces the activation class with the same specificity. Native answer
// attributes drive feedback directly, including undo and newly inserted inputs.
let css = template[1]
    .replaceAll('html.${ROOT_CLASS}.${CORRECT_CLASS}', 'html:root:has(.quiz-input__input-container[correct]:not([correct="false"]):not([incorrect]))')
    .replaceAll('html.${ROOT_CLASS}.${INCORRECT_CLASS}', 'html:root:has(.quiz-input__input-container:is([incorrect], [correct="false"]))')
    .replaceAll('html.${ROOT_CLASS}', 'html:root')
    .replaceAll('.days-studied-widget__background--dark', '.days-studied-widget__background')
if (css.includes('${')) throw new Error('Unconverted template interpolation')
css = css.replace(/^ {12}/gm, '').trim()

// CSS cannot add WaniKani's --dark class. Reference its existing dark assets
// directly; keep these four URLs in one manifest so asset changes are easy to update.
const assets = JSON.parse(await readFile(new URL('./days-studied-assets.json', import.meta.url), 'utf8'))
const artwork = Object.entries(assets).map(([palette, url]) => {
    if (!/^https:\/\/assets\.wanikani\.com\/assets\/widgets\/days-studied\/[a-z-]+-[a-f0-9]+\.svg$/.test(url)) {
        throw new Error(`Unexpected artwork URL for ${palette}`)
    }
    const ancestor = palette === 'default' ? '' : `.theme--${palette} `
    return `html:root ${ancestor}.days-studied-widget__background {\n    background-image: url("${url}");\n}`
}).join('\n\n')
const home = metadata('homepageURL')
const output = `/* ==UserStyle==
@name         ${metadata('name')}
@namespace    ${home}
@version      ${metadata('version')}
@description  ${metadata('description')}
@author       cabe9
@homepageURL  ${home}
@supportURL   ${metadata('supportURL')}
@updateURL    https://raw.githubusercontent.com/cabe9/wanikani-dark-mode/main/wanikani-dark-mode.user.css
@license      ${metadata('license')}
==/UserStyle== */

/* Generated by tools/build-usercss.mjs from review-dark-mode.user.js.
   Install with Stylus; enable only one edition of this theme at a time.
   Requires a browser with CSS :has() support. No theme JavaScript is needed. */

@-moz-document url-prefix("https://www.wanikani.com/"), url-prefix("https://preview.wanikani.com/") {
${[css, '/* Native dark artwork; the site still supplies the animation and spaceship. */', artwork].join('\n\n').split('\n').map(line => line ? '    ' + line : '').join('\n')}
}
`

if (process.argv.includes('--check')) {
    if (await readFile(outputPath, 'utf8') !== output) throw new Error('UserCSS is out of date; run tools/build-usercss.mjs')
    console.log('UserCSS matches the shared theme source')
} else {
    await mkdir(dirname(outputPath), {recursive: true})
    await writeFile(outputPath, output)
    console.log(`Built ${outputPath} (${metadata('version')})`)
}
